# EVENTS

TERMINATION = 0xFF

TIMEOUT = 0xFF01
UNKNOWN = 0xFF02
SERIAL_EVENTS = [TIMEOUT, UNKNOWN]

INIT = 0x00
ACTION_COMPLETE = 0x05
ACK = 0x06
UNABLE_TO_EXECUTE = 0x11
NACK = 0x15

CAMERA_EVENTS = [INIT, ACTION_COMPLETE, ACK, UNABLE_TO_EXECUTE, NACK]

# COMMAND
SETINT = 0x00
READINT = 0x01
ACTION = 0x02
READVDATA = 0x04

SHOT = [ACTION, 2]
LCD_MODE = [ACTION, 8]

FRAMES_COUNT = [READINT, 10]
FRAMES_CLEAR_LAST = [ACTION, 0]
FRAMES_LAST = [READINT, 11]
FRAMES_SELECT = [SETINT, 4]
FRAMES_GET = [READVDATA, 14]
FRAMES_GET_LENGTH = [READINT, 12]

# DATA
DATA_PACKET = 0x02
LAST_DATA_PACKET = 0x03
DATA_PREFIXES = [DATA_PACKET, LAST_DATA_PACKET]